### ISSUE TITLE
Go plugin, another

### ISSUE THREAD

**Issue by Alexey-T** [tike/GOnpp#4]
Thanks for this dll. Do you think it's possible to write it for SynWrite https://sourceforge.net/p/synwrite/wiki/Home/ ? 
ie, to adapt it?

**Comment by tike** [comment]
Hi Alexey,

sorry for replying so late, I missed to notice your issue.
Thanks for your interesst in the plugin and yes I'd generally think it is possible to do so.

When writing the code we tried to separate concerns properly, so it should not be too difficult to throw the basic code into a new plugin and wire the output up to the API of whatever GUI you're using.

**Comment by Alexey-T** [comment]
It';s good to hear. Indeed, needed good separation of code... I ll help with API of Synw..

**Comment by tike** [comment]
Hi Alexey,

I'm sorry, but there might be a missunderstanding: I would support you in porting the plugin to SynWrite, not the other way arround. That means, I'd answer your questions. If you want to have this ported, you'll have to code it yourself. I'm sorry, I can not be of more help rightnow, but I just don't have the time at the moment.

I'm very excited to see your interesst in the code
and wish you much success with your endeavour!

**Comment by Alexey-T** [comment]
I see now.Ok. Maybe you can create DLL from Go code, so that it gets info (autocomplete) and returns it in JSON/text?
If no, ok, let's close

**Comment by tike** [comment]
Ähm,

_gocode -f json ...._, does exactly that. So all you need to do, is write the code to execute the gocode executeable and digests the json afterwards.

As I said previously, I'm sorry, but I don't have the time to contribute to your project currently.
